### ISSUE TITLE
rarefaction across many samples

### ISSUE THREAD

**Issue by elsherbini** [swo/caravan#7]
often when comparing samples it's important to normalize the number of reads/sample somehow. The simplest and saddest way to do this is to define some threshhold, throw out all samples with fewer reads than that threshold, and sub-sample the other samples to have the same number of reads.

Is this a feature worth adding to caravan? Looks like QIIME has a python implementation: http://qiime.org/scripts/single_rarefaction.html (their github repo here: https://github.com/biocore/qiime/tree/master/scripts)

**Comment by swo** [comment]
I have a philosophical thing here: I only thought rarefying was good when
you were comparing, say, species richness between samples.

http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003531

what are other situations when it's demonstrably important?

**Comment by elsherbini** [comment]
this paper is well written and very helpful. Thanks! I guess I don't need no, rarefying after all.
